print("Time Utilisation Database")
n1=input("How much Hr do u study in a day?")
n1=eval(n1)
n2=input("How much Hr do you sleep in a day?")
n2=eval(n2)
n3=input("How much Hr do u use your phone?")
n3=eval(n3)
print("Mai nahi battaunga")
print("Shakal dekh le aayenen me")
print("pada raheta hai ek bistar par aur anime dekhta rehta hai aur yeh ",n2,"-",n2,"ghante toh sota hai ye")
print("Suaar!",n3,"ghante phone chalaye hai tune")
